### ISSUE TITLE
`npm run test` on fresh install

### ISSUE THREAD

**Issue by slor** [cerner/terra-framework#111]
# Issue Description
_npm run test_ command results in failures on fresh checkout and install.

```
Test Suites: 1 failed, 25 passed, 26 total
Tests:       6 failed, 159 passed, 165 total
Snapshots:   6 failed, 71 passed, 77 total
Time:        13.788s
```

Here is the full output of test command:

```
➜  terra-framework git:(master) npm run test

> terra-framework@0.1.0 pretest /Users/eh012472/src/terra-framework
> npm run lint


> terra-framework@0.1.0 lint /Users/eh012472/src/terra-framework
> npm run lint:js && npm run lint:scss


> terra-framework@0.1.0 lint:js /Users/eh012472/src/terra-framework
> eslint --ext .js,.jsx .


> terra-framework@0.1.0 lint:scss /Users/eh012472/src/terra-framework
> lerna run lint:scss

lerna info version 2.9.0
lerna info versioning independent

> terra-application-header-layout@2.1.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-application-header-layout
> stylelint src/**/*.scss


> terra-disclosure-manager@2.1.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-disclosure-manager
> stylelint src/**/*.scss


> terra-application-menu-layout@2.1.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-application-menu-layout
> stylelint src/**/*.scss


> terra-application-utility@0.0.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-application-utility
> stylelint src/**/*.scss


> terra-application-links@2.1.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-application-links
> stylelint src/**/*.scss


> terra-layout@2.1.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-layout
> stylelint src/**/*.scss


> terra-theme-provider@2.1.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-theme-provider
> stylelint src/**/*.scss


> terra-navigation-side-menu@1.0.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-navigation-side-menu
> stylelint src/**/*.scss


> terra-slide-panel-manager@2.1.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-slide-panel-manager
> stylelint src/**/*.scss


> terra-navigation-layout@2.1.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-navigation-layout
> stylelint src/**/*.scss


> terra-modal-manager@2.1.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-modal-manager
> stylelint src/**/*.scss


> terra-application-name@2.1.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-application-name
> stylelint src/**/*.scss


> terra-aggregator@2.1.0 lint:scss /Users/eh012472/src/terra-framework/packages/terra-aggregator
> stylelint src/**/*.scss

lerna success run Ran npm script 'lint:scss' in packages:
lerna success - terra-aggregator
lerna success - terra-application-header-layout
lerna success - terra-application-links
lerna success - terra-application-menu-layout
lerna success - terra-application-name
lerna success - terra-application-utility
lerna success - terra-disclosure-manager
lerna success - terra-layout
lerna success - terra-modal-manager
lerna success - terra-navigation-layout
lerna success - terra-navigation-side-menu
lerna success - terra-slide-panel-manager
lerna success - terra-theme-provider

> terra-framework@0.1.0 test /Users/eh012472/src/terra-framework
> jest && wdio

 PASS  packages/terra-aggregator/tests/jest/Aggregator.test.jsx
 PASS  packages/terra-navigation-layout/tests/jest/NavigationLayout.test.jsx
 PASS  packages/terra-application-header-layout/tests/jest/ApplicationHeader.test.jsx
 PASS  packages/terra-navigation-layout/tests/jest/RoutingStackDelegate.test.jsx
 FAIL  packages/terra-layout/tests/jest/Layout.test.jsx
  ● Layout › should render a Layout without optional props

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -5,11 +5,10 @@
        <LayoutSlidePanel
          isAnimated={true}
          isOpen={false}
          isToggleEnabled={false}
          onToggle={[Function]}
    -     panelBehavior="overlay"
          panelContent={null}
          size="tiny"
        >
          <ContentContainer
            fill={true}
      
      at Object.<anonymous> (packages/terra-layout/tests/jest/Layout.test.jsx:15:20)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● Layout › should render a Layout with custom props

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -6,11 +6,10 @@
        <LayoutSlidePanel
          isAnimated={true}
          isOpen={false}
          isToggleEnabled={false}
          onToggle={[Function]}
    -     panelBehavior="overlay"
          panelContent={null}
          size="tiny"
        >
          <ContentContainer
            fill={true}
      
      at Object.<anonymous> (packages/terra-layout/tests/jest/Layout.test.jsx:25:20)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● Layout › Menu Disabled › should render a Layout when tiny

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -5,11 +5,10 @@
        <LayoutSlidePanel
          isAnimated={true}
          isOpen={false}
          isToggleEnabled={false}
          onToggle={[Function]}
    -     panelBehavior="overlay"
          panelContent={null}
          size="tiny"
        >
          <ContentContainer
            fill={true}
      
      at Object.<anonymous> (packages/terra-layout/tests/jest/Layout.test.jsx:41:22)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● Layout › Menu Disabled › should render a Layout when small

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -5,11 +5,10 @@
        <LayoutSlidePanel
          isAnimated={true}
          isOpen={false}
          isToggleEnabled={false}
          onToggle={[Function]}
    -     panelBehavior="overlay"
          panelContent={null}
          size="small"
        >
          <ContentContainer
            fill={true}
      
      at Object.<anonymous> (packages/terra-layout/tests/jest/Layout.test.jsx:48:22)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● Layout › Menu Enabled › should render a Layout when tiny

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -5,11 +5,10 @@
        <LayoutSlidePanel
          isAnimated={true}
          isOpen={false}
          isToggleEnabled={false}
          onToggle={[Function]}
    -     panelBehavior="overlay"
          panelContent={
            <div
              layoutConfig={
                Object {
                  "menuIsOpen": false,
      
      at Object.<anonymous> (packages/terra-layout/tests/jest/Layout.test.jsx:88:22)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● Layout › Menu Enabled › should render a Layout when small

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -5,11 +5,10 @@
        <LayoutSlidePanel
          isAnimated={true}
          isOpen={false}
          isToggleEnabled={false}
          onToggle={[Function]}
    -     panelBehavior="overlay"
          panelContent={
            <div
              layoutConfig={
                Object {
                  "menuIsOpen": false,
      
      at Object.<anonymous> (packages/terra-layout/tests/jest/Layout.test.jsx:95:22)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

 › 6 snapshot tests failed.
 PASS  packages/terra-application-menu-layout/tests/jest/ApplicationMenu.test.jsx
 PASS  packages/terra-slide-panel-manager/tests/jest/SlidePanelManager.test.jsx
 PASS  packages/terra-modal-manager/tests/jest/actions.test.jsx
 PASS  packages/terra-layout/tests/jest/LayoutSlidePanel.test.jsx
 PASS  packages/terra-modal-manager/tests/jest/ModalManager.test.jsx
 PASS  packages/terra-application-name/tests/jest/ApplicationMenuName.test.jsx
 PASS  packages/terra-application-name/tests/jest/ApplicationHeaderName.test.jsx
 PASS  packages/terra-navigation-side-menu/tests/jest/NavigationSideMenu.test.jsx
 PASS  packages/terra-navigation-layout/tests/jest/RoutingStack.test.jsx (5.732s)
 PASS  packages/terra-navigation-layout/tests/jest/routingUtils.test.jsx (5.847s)
 PASS  packages/terra-app-delegate/tests/jest/AppDelegate.test.jsx (5.961s)
 PASS  packages/terra-theme-provider/tests/jest/ThemeProvider.test.jsx
 PASS  packages/terra-application-utility/tests/jest/ApplicationUtility.test.jsx
 PASS  packages/terra-navigation-layout/tests/jest/NavigationLayoutContent.test.jsx
 PASS  packages/terra-layout/tests/jest/LayoutUtils.test.js
 PASS  packages/terra-modal-manager/tests/jest/index.test.js (6.44s)
 PASS  packages/terra-app-delegate/tests/jest/DisclosureComponentRegistry.test.jsx
 PASS  packages/terra-modal-manager/tests/jest/reducers.test.jsx (6.497s)
 PASS  packages/terra-modal-manager/tests/jest/withModalManager.test.jsx
 PASS  packages/terra-disclosure-manager/tests/jest/DisclosureManager.test.jsx (6.813s)
 PASS  packages/terra-application-links/tests/jest/ApplicationTabs.test.jsx

Summary of all failing tests
 FAIL  packages/terra-layout/tests/jest/Layout.test.jsx
  ● Layout › should render a Layout without optional props

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -5,11 +5,10 @@
        <LayoutSlidePanel
          isAnimated={true}
          isOpen={false}
          isToggleEnabled={false}
          onToggle={[Function]}
    -     panelBehavior="overlay"
          panelContent={null}
          size="tiny"
        >
          <ContentContainer
            fill={true}
      
      at Object.<anonymous> (packages/terra-layout/tests/jest/Layout.test.jsx:15:20)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● Layout › should render a Layout with custom props

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -6,11 +6,10 @@
        <LayoutSlidePanel
          isAnimated={true}
          isOpen={false}
          isToggleEnabled={false}
          onToggle={[Function]}
    -     panelBehavior="overlay"
          panelContent={null}
          size="tiny"
        >
          <ContentContainer
            fill={true}
      
      at Object.<anonymous> (packages/terra-layout/tests/jest/Layout.test.jsx:25:20)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● Layout › Menu Disabled › should render a Layout when tiny

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -5,11 +5,10 @@
        <LayoutSlidePanel
          isAnimated={true}
          isOpen={false}
          isToggleEnabled={false}
          onToggle={[Function]}
    -     panelBehavior="overlay"
          panelContent={null}
          size="tiny"
        >
          <ContentContainer
            fill={true}
      
      at Object.<anonymous> (packages/terra-layout/tests/jest/Layout.test.jsx:41:22)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● Layout › Menu Disabled › should render a Layout when small

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -5,11 +5,10 @@
        <LayoutSlidePanel
          isAnimated={true}
          isOpen={false}
          isToggleEnabled={false}
          onToggle={[Function]}
    -     panelBehavior="overlay"
          panelContent={null}
          size="small"
        >
          <ContentContainer
            fill={true}
      
      at Object.<anonymous> (packages/terra-layout/tests/jest/Layout.test.jsx:48:22)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● Layout › Menu Enabled › should render a Layout when tiny

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -5,11 +5,10 @@
        <LayoutSlidePanel
          isAnimated={true}
          isOpen={false}
          isToggleEnabled={false}
          onToggle={[Function]}
    -     panelBehavior="overlay"
          panelContent={
            <div
              layoutConfig={
                Object {
                  "menuIsOpen": false,
      
      at Object.<anonymous> (packages/terra-layout/tests/jest/Layout.test.jsx:88:22)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● Layout › Menu Enabled › should render a Layout when small

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -5,11 +5,10 @@
        <LayoutSlidePanel
          isAnimated={true}
          isOpen={false}
          isToggleEnabled={false}
          onToggle={[Function]}
    -     panelBehavior="overlay"
          panelContent={
            <div
              layoutConfig={
                Object {
                  "menuIsOpen": false,
      
      at Object.<anonymous> (packages/terra-layout/tests/jest/Layout.test.jsx:95:22)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)


Snapshot Summary
 › 6 snapshot tests failed in 1 test suite. Inspect your code changes or run with `npm test -- -u` to update them.

Test Suites: 1 failed, 25 passed, 26 total
Tests:       6 failed, 159 passed, 165 total
Snapshots:   6 failed, 71 passed, 77 total
Time:        13.788s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terra-framework@0.1.0 test: `jest && wdio`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the terra-framework@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eh012472/.npm/_logs/2018-03-08T20_26_04_795Z-debug.log
```

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
All tests pass on fresh checkout, install

## Current Behavior
See above table in description.

## Steps to Reproduce
1. clone out https://github.com/cerner/terra-framework/
2. checkout master
3. npm install
4. npm run test

## Environment
* Component Version: master at daa8cb9c92bfe5e720bd63664b89612004f64452
* Browser Name and Version: n/a
* Operating System and version (desktop or mobile): macOS 10.12.6

Here is my env output:

```
➜  ~ env
TMPDIR=/var/folders/d3/qy2v11j16xx6pt0h1qgsdz4jmfzrbc/T/
XPC_FLAGS=0x0
SYMC_CUI_LI=1436738036
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.w0AN0u9mEH/Render
LANG=en_US.UTF-8
DISPLAY=/private/tmp/com.apple.launchd.medBHm5QJN/org.macosforge.xquartz:0
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.TtthDzm1YU/Listeners
SECURITYSESSIONID=186a5
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
XPC_SERVICE_NAME=0
TERM_PROGRAM_VERSION=388.1.1
TERM_SESSION_ID=17F8DB14-5341-455C-8745-7703221A0285
__CF_USER_TEXT_ENCODING=0x68EFE16C:0x0:0x0
SHELL=/usr/local/bin/zsh
HOME=/Users/eh012472
LOGNAME=eh012472
USER=eh012472
PATH=/Users/eh012472/.rbenv/shims:/Users/eh012472/.rbenv/bin:/Users/eh012472/.pyenv/shims:/Users/eh012472/bin:/Users/eh012472/.rbenv/shims:/Users/eh012472/.rbenv/bin:/Users/eh012472/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
SHLVL=1
PWD=/Users/eh012472
OLDPWD=/Users/eh012472
ZSH=/Users/eh012472/.oh-my-zsh
PAGER=less
LESS=-R
LC_CTYPE=en_US.UTF-8
LSCOLORS=Gxfxcxdxbxegedabagacad
HOMEBREW_GITHUB_API_TOKEN=cfe62d68b30254471a9f9ccf798c5d8ae4544e86
PYENV_SHELL=zsh
PYENV_VIRTUALENVWRAPPER_PYENV_VERSION=2.7.8
VIRTUALENVWRAPPER_PYTHON=/Users/eh012472/.pyenv/versions/2.7.8/bin/python
VIRTUALENVWRAPPER_VIRTUALENV=/Users/eh012472/.pyenv/versions/2.7.8/bin/virtualenv
VIRTUALENVWRAPPER_VIRTUALENV_CLONE=/Users/eh012472/.pyenv/versions/2.7.8/bin/virtualenv-clone
VIRTUALENVWRAPPER_SCRIPT=/Users/eh012472/.pyenv/versions/2.7.8/bin/virtualenvwrapper.sh
VIRTUALENVWRAPPER_LAZY_SCRIPT=/Users/eh012472/.pyenv/versions/2.7.8/bin/virtualenvwrapper_lazy.sh
VIRTUALENVWRAPPER_PROJECT_FILENAME=.project
VIRTUALENVWRAPPER_WORKON_CD=1
WORKON_HOME=/Users/eh012472/.virtualenvs
VIRTUALENVWRAPPER_HOOK_DIR=/Users/eh012472/.virtualenvs
PIP_FIND_LINKS=http://scm.healthe-axiom.cerner.corp/svn/axiom-python-services/trunk/ext/whl/ http://scm.healthe-axiom.cerner.corp/svn/axiom-python-services/trunk/ext/tgz/
PIP_TRUSTED_HOST=scm.healthe-axiom.cerner.corp
PROJECT_HOME=/Users/eh012472/Devel
RBENV_SHELL=zsh
_=/usr/bin/env
```

**Comment by mjhenkes** [comment]
I believe this is resolved with this PR https://github.com/cerner/terra-framework/pull/110

**Comment by bjankord** [comment]
One of our dependencies released a breaking change under a patch release that impacted our snapshot tests. https://github.com/adriantoine/enzyme-to-json/commit/b12686ade62593c873c61040bf5aac82227eb426

@slor I'm not sure if your team uses enzyme-to-json with your jest snapshots, thats the dependency that caused the issue for us. PR #110 resolves the issue.

**Comment by slor** [comment]
Confirmed, this is resolved for me after doing a pull, re-running npm install and test commands.
