### ISSUE TITLE
Hookshot not rendering properly on screen

### ISSUE THREAD

**Issue by Csgoodjr** [cerner/terra-framework#1556]
# Bug Report

## Description
When using any Terra component that utilizes the Hookshot component, it appears that it does not:
* translate to the proper location on the screen
* render the proper styles from the `scss` (including z-index)

This has been noticed across the Application Navigation & Select components:
![image](https://user-images.githubusercontent.com/5952721/163928159-67733be7-2c05-4b4d-ae24-3188ec530c78.png)
*See image above from Application Navigation*

From some initial investigation, it appears that other Terra components are having their styles properly imported, as the Select component is functional with the Dropdown styles and Dialog windows are functional with their respective styles. Additionally, the exported css-loader code can be seen in the Debugger tab under the Hookshot folder, yet it is the only style that does not seem to be passed along (this is confirmed by doing an inspection of the page and seeing all other styles with the exception of the `HookstotContent_module__*` CSS. 

I presume that this is an issue with the Webpack configuration and how it is handling the different imports. Our project is utilizing `Rails` with a `React` front-end. We are also using TypeScript, and have been declaring custom typing modules for the Terra Components -- to the best of our knowledge, this is not causing the issue, as this issue only occurs with some Terra components and not all. I will attach a copy of the config files below to see if there is anything glaring.

## Steps to Reproduce
1. Include component with a Hookshot dependency
2. Use component
3. Notice Hookshot styles not being utilized

## Additional Context / Screenshots
Application Navigation SCSS included properly: 
![image](https://user-images.githubusercontent.com/5952721/163932227-c238ca95-9a86-4f06-9b21-22da03271824.png)

Hookshot on same element/inspection window not being displayed:
![image](https://user-images.githubusercontent.com/5952721/163932891-85ea2173-5766-42fe-ab5c-ea90ead1f21c.png)

Webpack Config:
```
// Note: Rest can be found with @rails/webpacker default config
const { environment } = require('@rails/webpacker');

environment.loaders.append('typescript', {
    test: /.(ts|tsx)$/,
    loader: 'ts-loader'
});

environment.config.merge({
    performance: {
        maxEntrypointSize: 512000,
        maxAssetSize: 512000,
    }
});

module.exports = environment
```
Sample Render:
```
// Note: Not using Terra-Base due to another issue Terra-i18n -- assuming similar Webpack issue could be causing this
render(
    <IntlProvider
      locale="en"
      messages={messages}
    >
          <ApplicationNavigation
          id="admin-header"
          titleConfig={adminTitleConfig}
          userConfig={currentUserConfig}
          activeNavigationItemKey={currentUser?.userType ? route : "configuration"}
          navigationItems={
            currentUser?.userType === "system"
              ? systemAdminNavigationItems
              : contentAdminNavigationItems
          }
          onSelectNavigationItem={handleSelectNavigationItem}
          onSelectLogout={() => logUserOut()}
        >
          <Configuration />
        </ApplicationNavigation>
    </IntlProvider>,
    document.body.appendChild(container)
  );
```

## Expected Behavior
When using the Hookshot, it should render properly.

## Possible Solution
Currently, my best guess would be a Webpack issue, so if you have any input on how to better configure a Rails application for use with Terra, that would be incredibly helpful!

## Environment

* Component Name and Version: Hootshot
* Browser Name and Version: Firefox@latest
* Node/npm Version: Node v16.13.0, yarn v1.22.17
* Webpack Version: 4.46.0

**Comment by xenoworf** [comment]
Hello, and thanks for posting. We appreciate such a detailed issue report. 

My team took a look at your issue, and the first thing we noticed is that [the examples of hookshot in action, which are running our latest code, appear to be styling and rendering correctly](https://engineering.cerner.com/terra-ui/components/cerner-terra-framework-docs/hookshot/hookshot).  Since our examples seem to be working correctly, and since we have not received any other reports of this bug from our many users of this lib (it's used quite widely in our software stack here at Cerner), we think  the issue is probably with the config and asset setup - as you mentioned in your report. 

Here is the tricky part - Your setup of using @rails/webpacker and a custom webpack config, while not wrong, is something we can't debug ourselves. What we _can_ help you troubleshoot with is [using our standard webpack config that we support people extending](https://engineering.cerner.com/terra-ui/guides/terra-ui/basic-usage) (that getting started page links to the webpack config we support in more detail).  My idea for the next thing you should try would be making a new, empty project that extends our standard webpack config and see if you are still having the same problem. If you do, then we can help you investigate further from more of a common ground.

If you have questions about trying the standard webpack config idea let us know. Also, if you have any questions about the hookshot examples feel free to ask!  

Hope this helps.

**Comment by Csgoodjr** [comment]
Hi, thanks for the speedy response! I took your advice and spun off a new branch to play with the config. After installing the `@cerner/webpack-config-terra` package, I merged it in with the default `@rails/webpack` config and got this:

```
{
  mode: 'development',
  output: {
    filename: '[name].js',
    chunkFilename: '[name].js',
    hotUpdateChunkFilename: 'js/[id]-[hash].hot-update.js',
    path: '/Users/cjgood/my-care-team/build',
    publicPath: ''
  },
  resolve: {
    extensions: [
      '.tsx',         '.ts',
      '.mjs',         '.js',
      '.sass',        '.scss',
      '.css',         '.module.sass',
      '.module.scss', '.module.css',
      '.png',         '.svg',
      '.gif',         '.jpeg',
      '.jpg',         '.js',
      '.jsx'
    ],
    plugins: [ [Object] ],
    modules: [
      '/Users/cjgood/my-care-team/app/javascript',
      '/Users/cjgood/my-care-team/app/assets',
      '/Users/cjgood/my-care-team/app/javascript/models',
      'node_modules',
      'node_modules',
      'aggregated-translations'
    ],
    mainFields: [ 'browser', 'main' ]
  },
  resolveLoader: {
    modules: [ 'node_modules', '/Users/cjgood/my-care-team/node_modules' ],
    plugins: [ [Object] ]
  },
  node: {
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty'
  },
  devtool: 'eval-source-map',
  stats: { children: false },
  bail: true,
  optimization: { minimizer: [ [TerserPlugin] ] },
  performance: { maxEntrypointSize: 512000, maxAssetSize: 512000 },
  entry: {
    'admin/Configuration': '/Users/cjgood/my-care-team/app/javascript/packs/admin/Configuration.tsx',
    'admin/Home': '/Users/cjgood/my-care-team/app/javascript/packs/admin/Home.tsx',
    'admin/Index': '/Users/cjgood/my-care-team/app/javascript/packs/admin/Index.tsx',
    'admin/LogIn': '/Users/cjgood/my-care-team/app/javascript/packs/admin/LogIn.tsx',
    'admin/Providers': '/Users/cjgood/my-care-team/app/javascript/packs/admin/Providers.tsx',
    'admin/Reset': '/Users/cjgood/my-care-team/app/javascript/packs/admin/Reset.tsx',
    'admin/Users': '/Users/cjgood/my-care-team/app/javascript/packs/admin/Users.tsx',
    'admin/Welcome': '/Users/cjgood/my-care-team/app/javascript/packs/admin/Welcome.tsx',
    application: '/Users/cjgood/my-care-team/app/javascript/packs/application.js',
    'mycareteam/AddProvider': '/Users/cjgood/my-care-team/app/javascript/packs/mycareteam/AddProvider.tsx',
    'mycareteam/Index': '/Users/cjgood/my-care-team/app/javascript/packs/mycareteam/Index.tsx',
    'mycareteam/InitialAdd': '/Users/cjgood/my-care-team/app/javascript/packs/mycareteam/InitialAdd.tsx',
    'mycareteam/Profile': '/Users/cjgood/my-care-team/app/javascript/packs/mycareteam/Profile.tsx',
    'mycareteam/Scanner': '/Users/cjgood/my-care-team/app/javascript/packs/mycareteam/Scanner.tsx',
    'mycareteam/Search': '/Users/cjgood/my-care-team/app/javascript/packs/mycareteam/Search.tsx',
    'mycareteam/Welcome': '/Users/cjgood/my-care-team/app/javascript/packs/mycareteam/Welcome.tsx',
    'utils/createStyled': '/Users/cjgood/my-care-team/app/javascript/packs/utils/createStyled.ts'
  },
  module: {
    strictExportPresence: true,
    rules: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  plugins: [
    EnvironmentPlugin { keys: [Array], defaultValues: [Object] },
    CaseSensitivePathsPlugin {
      options: {},
      logger: [Object [console]],
      pathCache: Map(0) {},
      fsOperations: 0,
      primed: false
    },
    MiniCssExtractPlugin { options: [Object] },
    WebpackAssetsManifest {
      hooks: [Object],
      options: [Object],
      assets: [Object: null prototype] {},
      assetNames: Map(0) {},
      currentAsset: null,
      compiler: null,
      stats: null,
      hmrRegex: null,
      [Symbol(isMerging)]: false
    },
    CompressionPlugin {
      options: [Object],
      algorithm: [Function: asyncBufferWrapper],
      compressionOptions: [Object]
    },
    CompressionPlugin {
      options: [Object],
      algorithm: [Function: asyncBufferWrapper],
      compressionOptions: [Object]
    },
    OptimizeCssAssetsWebpackPlugin {
      pluginDescriptor: [Object],
      options: [Object],
      phaseAssetProcessors: [Object],
      deleteAssetsMap: {}
    },
    MiniCssExtractPlugin {
      _sortedModulesCache: [WeakMap],
      options: [Object],
      runtimeOptions: [Object]
    },
    PostCSSAssetsPlugin {
      test: /\.css$/,
      plugins: [Array],
      log: [Function (anonymous)]
    },
    DuplicatePackageCheckerPlugin { options: [Object] },
    DefinePlugin { definitions: [Object] }
  ],
  devServer: {
    host: '0.0.0.0',
    publicPath: '',
    stats: { colors: true, children: false }
  }
}
[terra-aggregate-translations] Aggregating translations for en,en-AU,en-CA,en-US,en-GB,es,es-US,es-ES,de,fr,fr-FR,nl,nl-BE,pt,pt-BR,sv,sv-SE locales.
```

For some reason though, I am getting this error from `source-map`: 
```Error: "version" is a required argument.
    at Object.getArg (/Users/cjgood/my-care-team/node_modules/source-map/lib/util.js:24:11)```

Do you have any advice on how to proceed? I will also attach the script that is merging these two:
```
// config/webpack/production.js
process.env.NODE_ENV = process.env.NODE_ENV || 'production'

const environment = require('./environment')
const { merge } = require('webpack-merge')

const defaultTerraConfig = require('@cerner/webpack-config-terra')
console.log(defaultTerraConfig())
console.log(environment.toWebpackConfig())

const mergedConfigs = merge(environment.toWebpackConfig(), defaultTerraConfig())
console.log(mergedConfigs)

module.exports = merge(environment.toWebpackConfig(), defaultTerraConfig())
```

**Comment by Csgoodjr** [comment]
Additionally, for completeness' sake, when I run this (reversing the order for merging), I get this error for each Terra Component:

```
ERROR in ./node_modules/terra-visually-hidden-text/lib/VisuallyHiddenText.module.scss (./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/postcss-loader/src??ref--4-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--4-oneOf-1-3!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js??ref--9-1!./node_modules/postcss-loader/src??ref--9-2!./node_modules/sass-loader/dist/cjs.js??ref--9-3!./node_modules/terra-visually-hidden-text/lib/VisuallyHiddenText.module.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: expected "{".
      ╷
    1 │ import api from "!../../style-loader/dist/runtime/injectStylesIntoStyleTag.js";
      │                                                                               ^
      ╵
      node_modules/terra-visually-hidden-text/lib/VisuallyHiddenText.module.scss 1:79  root stylesheet
```
// config/webpack/production.js
process.env.NODE_ENV = process.env.NODE_ENV || 'production'

const environment = require('./environment')
const { merge } = require('webpack-merge')

const defaultTerraConfig = require('@cerner/webpack-config-terra')

const themeConfig = { theme: 'terra-dark-theme' }

const mergedConfig = merge(
    defaultTerraConfig({}, {}, {themeConfig}),
    environment.toWebpackConfig()
)

console.log(mergedConfig)

module.exports = mergedConfig;
```

I'm assuming this is then one step closer, as the errors are shifting a bit, but not sure what to change to resolve this one. I did try and change the version of `sass-loader`, but that didn't yield any promising results.

**Comment by Csgoodjr** [comment]
Hi again, so I made a little more progress on a dummy application (https://github.com/Csgoodjr/terra-rails)

I implemented the Terra-Form-Select component and was able to get it to properly compile and run with TypeScript and all; however, I am still seeing the same issue as before. 

Feel free to give this a run and let me know what you think -- it is using the default Webpack-Terra-Config as well. 

Getting Started:
- Clone Repo
- Run `yarn build`
- Navigate to `localhost:3000/test` in your browser
- You should then be able to see the Terra component on the screen

Note: The issue we are seeing causes the Terra-Hookshot component to render unexpectedly on the page (even when setting the position style of the page to `fixed`). It can also be observed that the translations do not seem to be working properly either. This was also observed _before_ TypeScript was added as well.

<img width="1373" alt="Screen Shot 2022-04-20 at 6 02 46 PM" src="https://user-images.githubusercontent.com/5952721/164332521-b31c24a7-8fbb-4234-88f1-7bc5c1415ba6.png">

**Comment by xenoworf** [comment]
I tried cloning and building your project, but hit this error:
```
ERROR in ./app/javascript/packs/hello_react.tsx
Module build failed (from ./node_modules/ts-loader/index.js):
Error: A file specified in tsconfig.json could not be found: /Users/eh012472/Code/terra-rails/app/assets/javascripts/*.tsx
    at Object.loader (/Users/eh012472/Code/terra-rails/node_modules/ts-loader/dist/index.js:18:18)

error Command failed with exit code 1.
```

and indeed, I think you are referencing a non-existent dir:

![image](https://user-images.githubusercontent.com/52507228/164532385-fcf08e15-36db-4692-8a54-5bf18e5aa7fb.png)

I think if you investigate/fix this error we'll be a bit closer to the root cause of the problems.

**Comment by Csgoodjr** [comment]
Would it be possible to get a typical config with Rails and Webpacker for a Terra project? I keep running into build issues and then issues serving up that build.

**Comment by xenoworf** [comment]
I'll check with my team this morning to see what we've got handy.

**Comment by xenoworf** [comment]
**First, the bad news**: I spoke with my team, and we don't have any examples of using Terra with webpacker/rails since the terra project tries to be neutral about how it is integrated into various popular web frameworks (Rails, Django, etc.).

**The good news (kinda?)**, is that there is no reason to think you can't use Terra with webpacker/rails. In theory it can work fine - we just don't have a best practice we can refer you to. In theory - and I know this is cold comfort to you - it can work just fine to integrate Terra with your stack.

**Bonus:** I have gotten my hands on a sample empty project showing how to configure Terra in a "Hello, world!" fashion. I will post it back to you, but since it's company code (not open source) here at Cerner, it will take me some time to redact it and get it suitable to share. Once I have it, I will post back the relevant bits.

This is shown my team we have a gap in our documentation - that we don't do a very good job of showing a person who they can go from zero to "Hello, Terra!". Now that we know this, my goal is to turn the internal info I'm going to share with you on this thread into an update to our doc site (terra-ui.com) that will serve as a guide for our future users.

I expect I'll have this "Hello, world" example posted back to you early next week. Stay tuned until then 😄 .

**Comment by xenoworf** [comment]
OK slight change in plan: the code I thought would be a good example turned out to be highly confusing once I redacted out each of the proprietary bits.

Instead, if you are still interested in getting a webpack config for Terra up and running take a look at this page: https://engineering.cerner.com/terra-dev-site/dev_tools/terra-dev-site/terra-dev-site/about  

It's a bit meta, but that above page is a how-to guide for how to use Terra + webpack to spin up that very same site. Give it a try and see if that gets you to a working state; a site running using webpack and terra, and which will be rendering static content.

Please let me know how it goes.

**Comment by Csgoodjr** [comment]
After reviewing this page, it still doesn't seem like this is what we are asking for/need to integrate Terra into our site. From that working example, would it be possible to only get the `config/webpack/environment.js` and `config/webpack/production.js` files? Those are the only two files that we really need to make Terra Hookshot work in our Rails environment.

**Comment by xenoworf** [comment]
Hmmm, I'm not following. Best I can do is link you to the actual wepack config file for that project. If this doesn't help, then I'm out of steps to try. Lemme know and I can bring in another set of eyes who might be able to help.

https://github.com/cerner/terra-application/blob/main/webpack.config.js

**Comment by xenoworf** [comment]
Closing due to lack of activity. This can be re-opened if you have more questions.
